name: DCM
version: '${version}'
main: me.st4r.DCM.DCM
api-version: '1.21.11'
description: "Dams's Combat Mechanics - dual wielding, parry, axe combos, dash, adrenaline rush"
author: st4r

softdepend:
  - floodgate

commands:
  dash:
    description: Toggle your dash ability on or off
    usage: /dash
